bagtube_server:
  ros__parameters:
    pipes: [chatter, image_raw]
    chatter:
      type: std_msgs/String
      input_topic: /chatter
      output_topic: /chatter_stream
    image_raw:
      type: sensor_msgs/Image
      input_topic: /image_raw
      output_topic: /image_stream
